### ISSUE TITLE
Feature Request: Automatic recommendations

### ISSUE THREAD

**Issue by TheOne320** [Caseyy89/FlippingCalc#2]
Is there a way for you to auto pull the trade ratios from poe.ninja or directly from poe/trade and then display profitable flipping opportunities?

**Comment by Caseyy89** [comment]
This is a Feature i would love to add myself (Press a button, open a window with current prices for easy monitoring)
Unfortunately as a beginner i am learning as i go so this might take a while for me to figure out how to add, but id say planned (its a bit away tho).
